<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DSPPluginManager.Tests</AssemblyName>
    <RootNamespace>DSPPluginManager.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DSPPluginManager\DSPPluginManager.csproj" />
  </ItemGroup>
</Project>
